[project]
name = "goalstick"
version = "0.1.0"
description = ""
authors = [
    {name = "Matt B",email = "calicojack@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "nhl-api-py>=3.0.0",
    "python-dateutil",
    "pyserial",
    "sdnotify",
]

[project.optional-dependencies]
rpi = [
    "RPi.GPIO",
    "dbus-python",
]
dev = [
    "pytest>=7.0",
    "pytest-cov",
]

[tool.setuptools.packages.find]
include = ["StickCheck*"]


